<a href="https://colab.research.google.com/github/mariajulia-bds/Projetos-Python/blob/main/portifolio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Inserir 3 itens e binarizar caracteristicas. Em seguida, demonstrar a menor distância, imagens mais similares.

In [ ]:
# Dando caracteristicas a 'carro', 'moto', e 'bicicleta'.
# dentro de um {conjunto}, pra depois transforma em lista.

carro = {'roda','porta','retrovisor','marcha','freio','neutro','chave','combustivel'}
moto = {'freio','retrovisor','chave','marcha','neutro','roda','corrente'}
bicicleta = {'roda','ferio','pedal','guidão','corrente'}


In [136]:
# Preciso achar a união dos itens 'carro','moto','bicicleta'.
# A união entre eles vai virar o conjunto UNIVERSO
# usando o .union( ) = UNI

carro.union(moto).union(bicicleta)


{'chave',
 'combustivel',
 'corrente',
 'ferio',
 'freio',
 'guidão',
 'marcha',
 'neutro',
 'pedal',
 'porta',
 'retrovisor',
 'roda'}

In [137]:
universo = carro.union(moto).union(bicicleta)

In [138]:
# vou ter que importa o numpy da biblioteca para poder importa operações
# matemáticas de forma não manual.

import numpy as np


In [147]:
# NP.ISIN = retonar um array boleano onde cada valor vai ser true se estiver
# nos arrays correspondentes.
# NP.ARRAY =  operações matematicas com bastante eficiencia e rapidez.
# ASTYP(INT) = converte o array boleano do np.isin para array inteiro = (0,1).

# Quando eu quiser mostrar o resultado de cada um dos vetores é só eu escrever
# ex: un_carro

un = np.isin(list(universo), np.array(list(universo))).astype(int)
un_carro = np.isin(list(universo), np.array(list(carro))).astype(int)
un_moto = np.isin(list(universo), np.array(list(moto))).astype(int)
un_bicicleta = np.isin(list(universo), np.array(list(bicicleta))).astype(int)
un_carro

array([0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1])

In [141]:
un_bicicleta

array([1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0])

In [142]:
un_moto

array([0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0])

In [143]:
carro_moto = np.linalg.norm(un_carro - un_moto)
carro_moto


np.float64(1.7320508075688772)

In [144]:
moto_bicicleta = np.linalg.norm(un_moto - un_bicicleta)
moto_bicicleta

np.float64(2.8284271247461903)

In [145]:
carro_bicicleta =np.linalg.norm(un_carro - un_bicicleta)
carro_bicicleta

np.float64(3.3166247903554)

In [146]:
((carro_moto < moto_bicicleta) and (carro_moto < carro_bicicleta))*'carro_moto' +\
((moto_bicicleta < carro_bicicleta) and (moto_bicicleta < carro_moto))*'moto_bicicleta' +\
((carro_bicicleta < carro_moto) and (carro_bicicleta < moto_bicicleta))*'carro_bicicleta'



<ipython-input-146-d0dc42a1bf8f>:1: DeprecationWarning: In future, it will be an error for 'np.bool' scalars to be interpreted as an index
  ((carro_moto < moto_bicicleta) and (carro_moto < carro_bicicleta))*'carro_moto' +\
<ipython-input-146-d0dc42a1bf8f>:2: DeprecationWarning: In future, it will be an error for 'np.bool' scalars to be interpreted as an index
  ((moto_bicicleta < carro_bicicleta) and (moto_bicicleta < carro_moto))*'moto_bicicleta' +\
<ipython-input-146-d0dc42a1bf8f>:3: DeprecationWarning: In future, it will be an error for 'np.bool' scalars to be interpreted as an index
  ((carro_bicicleta < carro_moto) and (carro_bicicleta < moto_bicicleta))*'carro_bicicleta'


'carro_moto'

Inserir 3 itens e binarizar caracteristicas. Em seguida, demonstrar a menor distância, imagens mais similares.

In [109]:
# Dando caracteristicas a 'rosa', 'cacto', e 'girassol'.
# dentro de um {conjunto}, pra depois transforma em lista.

rosa = {'vermelha','espinho','petalas','caule'}
cacto = {'caule','espinho','verde'}
girassol = {'amarela','caule','semente','petalas'}

# Preciso achar a união dos itens 'rosa','cacto','girassol'.
# A união entre eles vai virar o conjunto UNIVERSO
# usando o .union( ) = UNI

universo = rosa.union(cacto).union(girassol)

# vou ter que importa o numpy da biblioteca para poder importa operações
# matemáticas de forma não manual.

import numpy as np

# NP.ISIN = retonar um array boleano onde cada valor vai ser true se estiver
# nos arrays correspondentes.
# NP.ARRAY =  operações matematicas com bastante eficiencia e rapidez.
# ASTYP(INT) = converte o array boleano do np.isin para array inteiro = (0,1).

un = np.isin(list(universo),np.array(list(universo))).astype(int)
un_rosa = np.isin(list(universo),np.array(list(rosa))).astype(int)
un_cacto = np.isin(list(universo),np.array(list(cacto))).astype(int)
un_girassol = np.isin(list(universo),np.array(list(girassol))).astype(int)

# Quando eu quiser mostrar o resultado de cada um dos vetores é só eu escrever
# ex: un_rosa =
un_rosa



array([1, 1, 0, 1, 0, 0, 1])

In [110]:
un_cacto

array([0, 0, 1, 1, 0, 0, 1])

In [111]:
un_girassol

array([1, 0, 0, 1, 1, 1, 0])

In [112]:
# NP.LINALG.NORM = ele faz a medição do 'tamanho', ou 'comprimento' dos vetores.

rosa_cacto = np.linalg.norm(un_rosa - un_cacto)
rosa_girassol = np.linalg.norm(un_rosa - un_girassol)
cacto_girassol = np.linalg.norm(un_cacto - un_girassol)

In [129]:
rosa_cacto

np.float64(1.7320508075688772)

In [130]:
rosa_girassol

np.float64(2.0)

In [131]:
cacto_girassol

np.float64(2.23606797749979)

In [128]:
((rosa_cacto < rosa_girassol) and (rosa_cacto < cacto_girassol))*'rosa cacto' +\
((rosa_girassol < rosa_cacto) and (rosa_girassol < cacto_girassol))*'rosa girassol' +\
((cacto_girassol < rosa_cacto) and (cacto_girassol < rosa_girassol))*'cacto girassol'

<ipython-input-128-9d6b797c3c3f>:1: DeprecationWarning: In future, it will be an error for 'np.bool' scalars to be interpreted as an index
  ((rosa_cacto < rosa_girassol) and (rosa_cacto < cacto_girassol))*'rosa cacto' +\
<ipython-input-128-9d6b797c3c3f>:2: DeprecationWarning: In future, it will be an error for 'np.bool' scalars to be interpreted as an index
  ((rosa_girassol < rosa_cacto) and (rosa_girassol < cacto_girassol))*'rosa girassol' +\
<ipython-input-128-9d6b797c3c3f>:3: DeprecationWarning: In future, it will be an error for 'np.bool' scalars to be interpreted as an index
  ((cacto_girassol < rosa_cacto) and (cacto_girassol < rosa_girassol))*'cacto girassol'


'rosa cacto'